### ISSUE TITLE
Boilerplate Rendering Issue

### ISSUE THREAD

**Issue by zeshraja1326** [Inlife/nexrender-boilerplate#14]
![nexrencer issue](https://user-images.githubusercontent.com/25750912/37077258-fc34f37e-21fb-11e8-90b3-ea1f6faf8141.PNG)

**Comment by inlife** [comment]
check, if there is any rendered file inside that folder

**Comment by ahyari** [comment]
@zeshraja1326 I faced the same issue, it turned out "After effect" is failing to render the video.
run the "After effect" command directly and check the error; following is the command generated by the tool
> aerender -comp  main -project  <path to project>\project.aep -output  <path to result>\result.mp4 -OMtemplate   h264 -e  3600

for me the errors were:
- -comp  main : I changed this to the project name
- -OMtemplate   h264 : this template wasn't in my After effect installation. you can check what option you have through after effect interface 'Edit -> Templates -> Output Modules' seeting name drop down list

Also open the project file and see if "After Effect" gives you any issue.

**Comment by zeshraja1326** [comment]
I checked it thoroughly and done it another way. thanks for response
